/**
 * Long-lived seed corpus for the development-only "Seed semantic test notes"
 * action surfaced in `NotesView.vue`. Lives under `dev/` so a dynamic import
 * can drop it from the production bundle.
 *
 * The shape mirrors the `SemanticSeedTemplate` interface declared in the
 * consumer; using `as const` here gives precise literal types for free.
 *
 * Do NOT touch the data without coordinating with the seeding flow — every
 * `key` is referenced by other entries' `links` array and broken cross
 * references silently degrade the seeded knowledge graph.
 */
export const longTermSeedTemplates = [
  {
    key: 'mira-valen',
    title: 'Mira Valen cartografa',
    kind: 'character',
    tags: ['archivio-vivo', 'cartografia', 'marea', 'inchieste'],
    body: [
      'Mira Valen aggiorna mappe costiere usando correnti, voci di porto e misure prese sui pontili dopo il tramonto. Tiene quaderni separati per canali sicuri, relitti mobili, fondali salati e rotte che cambiano dopo ogni mareggiata.',
      'Negli ultimi anni ha confrontato le mappe ufficiali con appunti rubati ai capitani. Le discrepanze piu ricorrenti puntano verso segnali di marea nera, contratti opachi e passaggi secondari sotto il vecchio faro.',
    ],
    links: ['cartografo-maree', 'bussola-correnti', 'gilda-bussole', 'processo-mappe-false'],
    searchHints: ['cartografa', 'mappe false', 'rotte costiere', 'marea'],
  },
  {
    key: 'orun-mastro',
    title: 'Orun il mediatore del porto',
    kind: 'character',
    tags: ['diplomazia', 'porto', 'sciopero', 'negoziati'],
    body: [
      'Orun risolve dispute tra equipaggi, scaricatori e doganieri con una pazienza quasi rituale. Conosce i turni dei battelli, i debiti nascosti e le parole giuste per far ripartire una trattativa prima che diventi rissa.',
      'Dopo lo sciopero dei battelli ha iniziato a conservare copie private di accordi, multe e promesse verbali. Le sue note sono preziose quando una fazione nega di aver preso parte a un blocco del molo.',
    ],
    links: ['mediatore-porto', 'sciopero-battelli', 'contratto-sette-banchine', 'consiglio-maree'],
    searchHints: ['mediatore', 'negoziazione', 'sciopero', 'porto'],
  },
  {
    key: 'selene-registri',
    title: 'Selene dei registri bassi',
    kind: 'character',
    tags: ['archivio', 'segreti', 'registri', 'custodi'],
    body: [
      'Selene cataloga documenti umidi nelle stanze sotto il municipio. Sa riconoscere una pagina riscritta dal colore della colla, dal ritmo delle cancellature e dal peso diverso della carta sotto le dita.',
      'Ha trovato rimandi ripetuti a sigilli sotto Eron e a voci dormienti nei margini di inventari senza valore apparente. Per prudenza conserva copie cifrate dentro fascicoli di manutenzione.',
    ],
    links: ['custodi-archivio-basso', 'sigilli-sotto-eron', 'archivio-voci-dormienti', 'archivista-campo'],
    searchHints: ['archivio basso', 'sigilli', 'registri alterati', 'documenti'],
  },
  {
    key: 'daro-chiuse',
    title: 'Daro delle chiuse',
    kind: 'character',
    tags: ['manutenzione', 'diga', 'chiuse', 'tecnico'],
    body: [
      'Daro conosce ogni bullone delle chiuse orientali. Segna vibrazioni, pressione dell acqua e colore della ruggine, poi confronta i dati con una memoria pratica costruita in venti inverni di guasti.',
      'Dopo l incendio della diga vecchia ha imposto turni di ispezione piu brevi. La sua lista di interventi distingue tra rischio reale, panico del consiglio e danni lasciati in silenzio per risparmiare fondi.',
    ],
    links: ['tecnico-chiuse', 'incendio-diga-vecchia', 'chiave-ruggine-dolce', 'checklist-riparazioni'],
    searchHints: ['chiuse', 'diga', 'ruggine', 'manutenzione'],
  },
  {
    key: 'nima-serra',
    title: 'Nima della serra salmastra',
    kind: 'character',
    tags: ['erbe', 'serra', 'cura', 'sale'],
    body: [
      'Nima coltiva piante capaci di vivere tra acqua dolce e acqua salata. I suoi appunti registrano odori, fioriture lente, reazioni a polveri minerali e rimedi preparati per febbri da molo.',
      'La serra e diventata un archivio parallelo: ogni vaso ha una storia, ogni talea una provenienza. Alcune specie reagiscono alla marea nera chiudendo le foglie molto prima che il fenomeno sia visibile.',
    ],
    links: ['erbario-nima', 'maree-nere', 'figli-sale', 'appunti-cucina-molo'],
    searchHints: ['serra salmastra', 'erbe medicinali', 'piante', 'marea nera'],
  },
  {
    key: 'talia-cartaccia',
    title: 'Talia Cartaccia',
    kind: 'character',
    tags: ['contrabbando', 'lanterne', 'testimone', 'inchiesta'],
    body: [
      'Talia raccoglie ricevute, biglietti bruciati e frammenti di timbri doganali. Dice che la carta racconta la verita quando le persone hanno gia deciso quale bugia usare.',
      'Ha collegato una serie di lampade a vetro freddo a consegne notturne e al processo delle mappe false. Le sue prove sono fragili ma indicano una rete piu ampia del semplice contrabbando.',
    ],
    links: ['lampada-vetro-freddo', 'officina-lanterne', 'processo-mappe-false', 'quartiere-lanterne'],
    searchHints: ['contrabbando', 'prove cartacee', 'lampade', 'inchiesta'],
  },
  {
    key: 'nacreani',
    title: 'Nacreani',
    kind: 'race',
    tags: ['popolo', 'nacre', 'lingua', 'osservatorio'],
    body: [
      'I Nacreani abitano terrazze chiare intorno all osservatorio e usano registri sonori per tramandare misure astronomiche. La loro scrittura alterna incisioni sottili e pause che indicano il respiro del lettore.',
      'Nelle traduzioni piu antiche non separano scienza, genealogia e preghiera. Una nota di rotta puo contenere anche un ricordo famigliare e una previsione sulle maree.',
    ],
    links: ['osservatorio-nacre', 'lingua-nacreana', 'spedizione-nacre', 'selene-registri'],
    searchHints: ['Nacreani', 'lingua', 'osservatorio', 'scrittura'],
  },
  {
    key: 'figli-sale',
    title: 'Figli del Sale',
    kind: 'race',
    tags: ['popolo', 'sale blu', 'miniera', 'adattamento'],
    body: [
      'I Figli del Sale lavorano vene minerali che colorano pelle, vestiti e strumenti con riflessi azzurri. Portano maschere leggere non per paura della polvere, ma per riconoscere il grado di purezza dal sapore dell aria.',
      'Molti vivono tra miniera e porto, dividendo l anno in stagioni di estrazione e stagioni di mercato. Le loro canzoni descrivono percorsi sotterranei meglio di molte mappe ufficiali.',
    ],
    links: ['miniera-sale-blu', 'compagnia-sale-blu', 'nima-serra', 'cronologia-luna-spezzata'],
    searchHints: ['sale blu', 'miniera', 'popolo minerario', 'maschere'],
  },
  {
    key: 'veyrani',
    title: 'Veyrani del bosco interno',
    kind: 'race',
    tags: ['popolo', 'bosco', 'rituali', 'memoria'],
    body: [
      'I Veyrani conservano memoria dei sentieri con nodi, semi e piccole pietre lucide. Ogni famiglia riconosce una parte del bosco come se fosse una stanza di casa, anche quando gli alberi cambiano forma dopo le piogge.',
      'Accolgono visitatori solo durante la festa delle braci chiare. In quei giorni le storie sui segni della Luna Spezzata vengono cantate senza strumenti, per non svegliare le voci dormienti.',
    ],
    links: ['bosco-veyra', 'festa-braci-chiare', 'archivio-voci-dormienti', 'cronologia-luna-spezzata'],
    searchHints: ['Veyrani', 'bosco', 'rituali', 'memoria orale'],
  },
  {
    key: 'cartografo-maree',
    title: 'Cartografo delle maree',
    kind: 'class',
    tags: ['professione', 'mappe', 'correnti', 'maree'],
    body: [
      'Il cartografo delle maree misura territori che non restano mai fermi. Deve leggere vento, schiuma, rumore delle catene e testimonianze dei barcaioli prima di tracciare una rotta utile.',
      'La formazione include geometria pratica, astronomia bassa, archiviazione delle varianti e uso di bussole sensibili alla corrente. Gli errori non sono accademici: una linea sbagliata puo affondare un carico.',
    ],
    links: ['mira-valen', 'bussola-correnti', 'gilda-bussole', 'porto-vetro'],
    searchHints: ['cartografo', 'correnti', 'mappe', 'marea'],
  },
  {
    key: 'mediatore-porto',
    title: 'Mediatore di porto',
    kind: 'class',
    tags: ['professione', 'negoziati', 'porto', 'accordi'],
    body: [
      'Il mediatore di porto e una figura ibrida: parte notaio, parte arbitro, parte memoria vivente. Lavora tra banchine, sale doganali e taverne dove gli accordi vengono spesso stretti prima di essere scritti.',
      'Un buon mediatore sa quando registrare una promessa, quando fingere di non averla sentita e quando chiamare testimoni. La neutralita vale solo se tutte le parti credono di poter perdere qualcosa.',
    ],
    links: ['orun-mastro', 'contratto-sette-banchine', 'sciopero-battelli', 'consiglio-maree'],
    searchHints: ['mediatore', 'accordi', 'dogana', 'negoziato'],
  },
  {
    key: 'archivista-campo',
    title: 'Archivista di campo',
    kind: 'class',
    tags: ['professione', 'archivio', 'rilievi', 'fonti'],
    body: [
      'L archivista di campo porta il metodo fuori dalle sale ordinate. Raccoglie testimonianze in luoghi sporchi, conserva campioni, assegna indici provvisori e annota cosa potrebbe diventare prova in seguito.',
      'Questa classe nasce dopo il processo delle mappe false, quando divenne chiaro che una fonte non verificata poteva cambiare una sentenza. Ogni appunto deve indicare provenienza, ora e grado di fiducia.',
    ],
    links: ['selene-registri', 'processo-mappe-false', 'custodi-archivio-basso', 'frammento-senza-provenienza'],
    searchHints: ['archivista', 'prove', 'fonti', 'catalogazione'],
  },
  {
    key: 'tecnico-chiuse',
    title: 'Tecnico delle chiuse',
    kind: 'class',
    tags: ['professione', 'ingegneria', 'diga', 'manutenzione'],
    body: [
      'Il tecnico delle chiuse mantiene il confine tra citta e acqua. Lavora con pressioni, valvole, legno gonfio, ruggine e squadre stanche che devono fidarsi di istruzioni brevi durante una piena.',
      'La formazione richiede apprendistato sul campo e lettura di registri di guasto. Dopo ogni inverno il tecnico aggiorna procedure, strumenti e percorsi di evacuazione.',
    ],
    links: ['daro-chiuse', 'incendio-diga-vecchia', 'chiave-ruggine-dolce', 'checklist-riparazioni'],
    searchHints: ['tecnico', 'chiuse', 'diga', 'manutenzione'],
  },
  {
    key: 'porto-vetro',
    title: 'Porto di Vetro',
    kind: 'location',
    tags: ['luogo', 'porto', 'commercio', 'maree'],
    body: [
      'Il Porto di Vetro prende nome dai frangiflutti lucidi che riflettono le luci delle navi. Di giorno sembra ordinato, ma di notte le banchine si dividono in territori non dichiarati.',
      'Qui arrivano sale blu, strumenti di Nacre, piante salmastre e contratti con clausole scritte in margine. La ricerca semantica dovrebbe collegare il porto a mediazione, scioperi, mappe e commercio.',
    ],
    links: ['orun-mastro', 'sciopero-battelli', 'contratto-sette-banchine', 'diario-mercato'],
    searchHints: ['porto', 'banchine', 'commercio', 'sciopero'],
  },
  {
    key: 'bosco-veyra',
    title: 'Bosco di Veyra',
    kind: 'location',
    tags: ['luogo', 'bosco', 'rituale', 'sentieri'],
    body: [
      'Il Bosco di Veyra e difficile da mappare perche i sentieri cambiano dopo piogge lunghe e perche gli abitanti rimuovono segnali estranei. Le radure usate nei rituali non sono segnate su carte pubbliche.',
      'Chi entra senza guida torna con racconti incoerenti: alberi che sembrano ripetersi, luci basse, cenere fredda tra le radici. I Veyrani distinguono paura, memoria e cattivo orientamento con molta precisione.',
    ],
    links: ['veyrani', 'festa-braci-chiare', 'cronologia-luna-spezzata', 'registro-sogni'],
    searchHints: ['bosco', 'Veyra', 'sentieri', 'rituali'],
  },
  {
    key: 'miniera-sale-blu',
    title: 'Miniera del Sale Blu',
    kind: 'location',
    tags: ['luogo', 'miniera', 'sale blu', 'estrazione'],
    body: [
      'La Miniera del Sale Blu scende in camere umide dove la luce diventa lattiginosa. I turni sono brevi, i canti sono obbligatori e ogni silenzio improvviso viene trattato come segnale di crollo.',
      'La compagnia controlla pesi, accessi e registri medici. Alcune gallerie abbandonate portano simboli simili ai sigilli sotto Eron, ma nessuno li nomina durante le ispezioni ufficiali.',
    ],
    links: ['figli-sale', 'compagnia-sale-blu', 'sigilli-sotto-eron', 'nima-serra'],
    searchHints: ['sale blu', 'miniera', 'estrazione', 'sigilli'],
  },
  {
    key: 'osservatorio-nacre',
    title: 'Osservatorio di Nacre',
    kind: 'location',
    tags: ['luogo', 'astronomia', 'nacre', 'maree'],
    body: [
      'L Osservatorio di Nacre e costruito su terrazze che raccolgono vento e sale. Le sale superiori leggono il cielo, quelle inferiori archiviano maree e genealogie in registri sonori.',
      'La spedizione piu recente ha trovato strumenti allineati con la Luna Spezzata. Alcuni valori anticipano maree nere e anomalie nelle bussole costiere.',
    ],
    links: ['nacreani', 'spedizione-nacre', 'lingua-nacreana', 'maree-nere'],
    searchHints: ['osservatorio', 'Nacre', 'astronomia', 'marea nera'],
  },
  {
    key: 'quartiere-lanterne',
    title: 'Quartiere delle Lanterne',
    kind: 'location',
    tags: ['luogo', 'lanterne', 'artigiani', 'contrabbando'],
    body: [
      'Il Quartiere delle Lanterne ospita officine, botteghe e cortili stretti dove il vetro viene raffreddato con acqua salata. Di sera le insegne colorate rendono quasi impossibile seguire qualcuno.',
      'Da mesi circolano lampade a vetro freddo fuori registro. Alcuni pezzi finiscono nei carichi del porto prima di passare per la dogana, segno di un accordo interno.',
    ],
    links: ['officina-lanterne', 'lampada-vetro-freddo', 'talia-cartaccia', 'porto-vetro'],
    searchHints: ['lanterne', 'officine', 'contrabbando', 'vetro freddo'],
  },
  {
    key: 'bussola-correnti',
    title: 'Bussola delle Correnti',
    kind: 'item',
    tags: ['oggetto', 'bussola', 'mappe', 'marea'],
    body: [
      'La Bussola delle Correnti non punta il nord, ma la trazione dell acqua sotto la chiglia. Il quadrante vibra quando incontra sale blu raffinato o quando la marea nera si avvicina alle foci.',
      'Mira Valen la usa con cautela perche una lettura isolata puo mentire. Serve confrontarla con stelle basse, rumore dei cavi e memoria dei battellieri.',
    ],
    links: ['mira-valen', 'cartografo-maree', 'maree-nere', 'gilda-bussole'],
    searchHints: ['bussola', 'correnti', 'marea', 'mappe'],
  },
  {
    key: 'lampada-vetro-freddo',
    title: 'Lampada a Vetro Freddo',
    kind: 'item',
    tags: ['oggetto', 'lampada', 'vetro', 'contrabbando'],
    body: [
      'La lampada a vetro freddo emette luce stabile senza scaldare il metallo. Gli artigiani dicono che serve per archivi umidi, ma i contrabbandieri la preferiscono per leggere sigilli senza consumare ossigeno.',
      'I modelli recenti portano incisioni minuscole dietro il perno. Talia sostiene che quelle incisioni coincidano con consegne annotate solo su ricevute bruciate.',
    ],
    links: ['talia-cartaccia', 'officina-lanterne', 'quartiere-lanterne', 'sigilli-sotto-eron'],
    searchHints: ['lampada', 'vetro freddo', 'contrabbando', 'sigilli'],
  },
  {
    key: 'chiave-ruggine-dolce',
    title: 'Chiave di Ruggine Dolce',
    kind: 'item',
    tags: ['oggetto', 'chiave', 'diga', 'ruggine'],
    body: [
      'La chiave di ruggine dolce apre i pannelli piu vecchi delle chiuse. Il nome viene dall odore metallico lasciato sulle mani quando la lega reagisce con acqua salmastra.',
      'Daro la conserva in una scatola cerata e la usa solo in emergenza. Dopo l incendio della diga vecchia e diventata prova materiale in una disputa sulle responsabilita tecniche.',
    ],
    links: ['daro-chiuse', 'tecnico-chiuse', 'incendio-diga-vecchia', 'checklist-riparazioni'],
    searchHints: ['chiave', 'ruggine', 'chiuse', 'diga'],
  },
  {
    key: 'erbario-nima',
    title: 'Erbario di Nima',
    kind: 'item',
    tags: ['oggetto', 'erbario', 'piante', 'cura'],
    body: [
      'L Erbario di Nima contiene foglie pressate, semi salati, ricette di infusi e note sulle reazioni a minerali blu. Ogni pagina ha una scala di odore e una piccola mappa del luogo di raccolta.',
      'Alcune piante sembrano ricordare eventi di marea. Se raccolte dopo una notte nera, rilasciano colore scuro anche settimane piu tardi.',
    ],
    links: ['nima-serra', 'maree-nere', 'figli-sale', 'appunti-cucina-molo'],
    searchHints: ['erbario', 'piante', 'cura', 'marea nera'],
  },
  {
    key: 'contratto-sette-banchine',
    title: 'Contratto delle Sette Banchine',
    kind: 'item',
    tags: ['documento', 'contratto', 'porto', 'accordi'],
    body: [
      'Il contratto regola turni, pedaggi e precedenze tra sette banchine del Porto di Vetro. Le clausole laterali sono piu importanti del testo principale e cambiano valore a seconda della stagione.',
      'Orun ne conserva una copia annotata con firme, cancellature e promesse verbali. Durante lo sciopero dei battelli ogni fazione ha citato una versione diversa dello stesso documento.',
    ],
    links: ['orun-mastro', 'sciopero-battelli', 'consiglio-maree', 'porto-vetro'],
    searchHints: ['contratto', 'banchine', 'porto', 'sciopero'],
  },
  {
    key: 'gilda-bussole',
    title: 'Gilda delle Bussole',
    kind: 'faction',
    tags: ['fazione', 'cartografia', 'rotte', 'strumenti'],
    body: [
      'La Gilda delle Bussole certifica strumenti, rotte e cartografi. Ufficialmente protegge la navigazione, ma controlla anche quali mappe possono diventare documenti pubblici.',
      'Dopo il processo delle mappe false la gilda ha perso autorita e ha iniziato a finanziare rilievi privati. Mira Valen collabora con loro solo quando puo controllare i dati grezzi.',
    ],
    links: ['mira-valen', 'cartografo-maree', 'bussola-correnti', 'processo-mappe-false'],
    searchHints: ['gilda', 'bussole', 'cartografia', 'mappe false'],
  },
  {
    key: 'compagnia-sale-blu',
    title: 'Compagnia del Sale Blu',
    kind: 'faction',
    tags: ['fazione', 'miniera', 'commercio', 'sale blu'],
    body: [
      'La Compagnia del Sale Blu possiede carrelli, magazzini, medici e quasi tutti i debiti dei minatori. Il suo potere nasce dal controllo delle bilance prima ancora che dalla proprieta delle gallerie.',
      'Quando una vena cambia colore, la compagnia chiude il tratto e sposta i registri. Selene sospetta che i dati sanitari vengano riscritti prima di arrivare agli archivi pubblici.',
    ],
    links: ['miniera-sale-blu', 'figli-sale', 'selene-registri', 'diario-mercato'],
    searchHints: ['compagnia', 'sale blu', 'minatori', 'registri sanitari'],
  },
  {
    key: 'consiglio-maree',
    title: 'Consiglio delle Maree',
    kind: 'faction',
    tags: ['fazione', 'governo', 'porto', 'maree'],
    body: [
      'Il Consiglio delle Maree decide aperture delle chiuse, tariffe portuali e priorita dei soccorsi. Ogni membro rappresenta un equilibrio tra quartieri, compagnie e vecchie famiglie del litorale.',
      'Le decisioni piu delicate vengono motivate con grafici sulla sicurezza, ma spesso nascondono pressioni di banchina. Orun conosce le frasi usate quando il consiglio vuole sembrare neutrale.',
    ],
    links: ['orun-mastro', 'contratto-sette-banchine', 'incendio-diga-vecchia', 'sciopero-battelli'],
    searchHints: ['consiglio', 'maree', 'governo', 'tariffe'],
  },
  {
    key: 'custodi-archivio-basso',
    title: 'Custodi dell Archivio Basso',
    kind: 'faction',
    tags: ['fazione', 'archivio', 'custodi', 'segreti'],
    body: [
      'I Custodi dell Archivio Basso proteggono registri danneggiati, documenti scomodi e collezioni che nessun ufficio vuole nominare. L umidita e parte del sistema: rallenta furti e scoraggia curiosi.',
      'La fazione non e militare, ma possiede una disciplina feroce. Ogni custode impara a riconoscere falsi, muffe e mani che hanno paura di lasciare tracce.',
    ],
    links: ['selene-registri', 'archivista-campo', 'archivio-voci-dormienti', 'sigilli-sotto-eron'],
    searchHints: ['custodi', 'archivio basso', 'falsi', 'registri'],
  },
  {
    key: 'officina-lanterne',
    title: 'Officina delle Lanterne',
    kind: 'faction',
    tags: ['fazione', 'artigiani', 'vetro', 'lanterne'],
    body: [
      'L Officina delle Lanterne e una corporazione di vetrai, lucidatori e tecnici della luce. Produce strumenti per porti, archivi e squadre di manutenzione che lavorano in ambienti saturi di sale.',
      'La reputazione pubblica e solida, ma alcune partite non compaiono nei registri. Talia segue proprio quelle lampade per ricostruire passaggi tra quartiere artigiano e banchine.',
    ],
    links: ['quartiere-lanterne', 'lampada-vetro-freddo', 'talia-cartaccia', 'porto-vetro'],
    searchHints: ['officina', 'lanterne', 'vetro', 'partite non registrate'],
  },
  {
    key: 'incendio-diga-vecchia',
    title: 'Incendio della Diga Vecchia',
    kind: 'event',
    tags: ['evento', 'diga', 'incendio', 'emergenza'],
    body: [
      'L incendio della diga vecchia inizio durante una notte di vento basso, quando nessuno si aspettava fiamme vicino a tanta acqua. Bruciarono passerelle, depositi di grasso e parte dei registri tecnici.',
      'Le indagini produssero versioni incompatibili: incidente, sabotaggio, negligenza o copertura finanziaria. Daro conserva una cronologia tecnica piu precisa delle deposizioni ufficiali.',
    ],
    links: ['daro-chiuse', 'tecnico-chiuse', 'chiave-ruggine-dolce', 'consiglio-maree'],
    searchHints: ['incendio', 'diga', 'sabotaggio', 'emergenza'],
  },
  {
    key: 'festa-braci-chiare',
    title: 'Festa delle Braci Chiare',
    kind: 'event',
    tags: ['evento', 'rituale', 'bosco', 'Veyra'],
    body: [
      'La Festa delle Braci Chiare apre il Bosco di Veyra agli ospiti per una sola notte. Ogni fuoco deve consumare legna raccolta senza ferro, e ogni racconto viene ripetuto tre volte da voci diverse.',
      'Negli ultimi anni i sogni dei visitatori sono diventati piu simili tra loro. Alcuni archivisti sospettano un legame con le voci dormienti e con la cronologia della Luna Spezzata.',
    ],
    links: ['bosco-veyra', 'veyrani', 'registro-sogni', 'archivio-voci-dormienti'],
    searchHints: ['festa', 'braci', 'Veyra', 'sogni ricorrenti'],
  },
  {
    key: 'spedizione-nacre',
    title: 'Spedizione a Nacre',
    kind: 'event',
    tags: ['evento', 'spedizione', 'nacre', 'astronomia'],
    body: [
      'La spedizione a Nacre parti con cartografi, archivisti e due tecnici delle bussole. Doveva verificare strumenti astronomici, ma torno con mappe di correnti e registrazioni sonore difficili da tradurre.',
      'Il rapporto finale fu diviso in tre fascicoli: osservazioni celesti, lingua nacreana e anomalie costiere. Solo il primo venne pubblicato senza tagli.',
    ],
    links: ['osservatorio-nacre', 'nacreani', 'lingua-nacreana', 'mira-valen'],
    searchHints: ['spedizione', 'Nacre', 'astronomia', 'traduzione'],
  },
  {
    key: 'sciopero-battelli',
    title: 'Sciopero dei Battelli',
    kind: 'event',
    tags: ['evento', 'sciopero', 'porto', 'lavoro'],
    body: [
      'Lo sciopero dei battelli blocco il Porto di Vetro per undici giorni. I magazzini si riempirono, le taverne diventarono sale riunioni e il consiglio dichiaro emergenza senza nominare le cause reali.',
      'Orun firmo tre tregue provvisorie e vide fallirne due. La terza resse perche collegava salari, turni e accesso alle banchine in un unico accordo.',
    ],
    links: ['orun-mastro', 'mediatore-porto', 'contratto-sette-banchine', 'porto-vetro'],
    searchHints: ['sciopero', 'battelli', 'salari', 'porto'],
  },
  {
    key: 'processo-mappe-false',
    title: 'Processo delle Mappe False',
    kind: 'event',
    tags: ['evento', 'processo', 'mappe', 'prove'],
    body: [
      'Il processo delle mappe false dimostro che una rotta alterata poteva spostare colpe, eredita e diritti di pesca. Le udienze trasformarono dettagli tecnici in accuse politiche.',
      'La sentenza non chiuse il caso. Da allora ogni mappa importante richiede fonte, data, strumento usato e almeno un confronto indipendente.',
    ],
    links: ['mira-valen', 'gilda-bussole', 'archivista-campo', 'talia-cartaccia'],
    searchHints: ['processo', 'mappe false', 'prove', 'rotte alterate'],
  },
  {
    key: 'cronologia-luna-spezzata',
    title: 'Cronologia della Luna Spezzata',
    kind: 'lore',
    tags: ['lore', 'luna', 'mitologia', 'cronologia'],
    body: [
      'La Luna Spezzata non e solo un mito: e una struttura cronologica usata da popoli diversi per datare maree anomale, nascite fuori stagione e variazioni nelle bussole.',
      'Le fonti non concordano sul primo segno. I Veyrani parlano di canti nel bosco, i Nacreani di misure celesti, i Figli del Sale di gallerie diventate blu in una notte.',
    ],
    links: ['veyrani', 'nacreani', 'figli-sale', 'maree-nere'],
    searchHints: ['Luna Spezzata', 'mitologia', 'cronologia', 'maree anomale'],
  },
  {
    key: 'sigilli-sotto-eron',
    title: 'Sigilli sotto Eron',
    kind: 'lore',
    tags: ['lore', 'sigilli', 'sotterranei', 'archivio'],
    body: [
      'I sigilli sotto Eron compaiono in miniera, archivi e vecchie fondamenta portuali. Non sono decorazioni: la ripetizione degli stessi tratti suggerisce un sistema di avvisi o chiusure.',
      'Selene ritiene che i sigilli segnino luoghi dove la memoria deve restare ferma. Talia invece li collega a lampade usate per leggere incisioni senza attivare reazioni chimiche.',
    ],
    links: ['selene-registri', 'miniera-sale-blu', 'lampada-vetro-freddo', 'custodi-archivio-basso'],
    searchHints: ['sigilli', 'Eron', 'sotterranei', 'archivio'],
  },
  {
    key: 'maree-nere',
    title: 'Teoria delle Maree Nere',
    kind: 'lore',
    tags: ['lore', 'marea nera', 'anomalia', 'ricerca'],
    body: [
      'La teoria delle maree nere descrive correnti scure che non seguono vento, luna o pressione. Appaiono prima come odore di ferro, poi come riflessi opachi vicino alle foci.',
      'Le note migliori incrociano bussole, piante salmastre, osservazioni di Nacre e registri dei battellieri. La ricerca semantica dovrebbe avvicinare query su anomalia, correnti, piante e strumenti.',
    ],
    links: ['bussola-correnti', 'erbario-nima', 'osservatorio-nacre', 'nima-serra'],
    searchHints: ['marea nera', 'correnti scure', 'anomalia', 'strumenti'],
  },
  {
    key: 'archivio-voci-dormienti',
    title: 'Archivio delle Voci Dormienti',
    kind: 'lore',
    tags: ['lore', 'voci', 'memoria', 'archivio'],
    body: [
      'Le voci dormienti sono registrazioni, canti o ricordi che sembrano attivarsi quando piu fonti raccontano la stessa cosa nello stesso luogo. Non e chiaro se siano fenomeno, tecnica o superstizione.',
      'I Custodi dell Archivio Basso conservano casi ripetuti: sogni uguali dopo la festa, note sonore di Nacre e testimonianze di minatori che ricordano parole mai udite.',
    ],
    links: ['custodi-archivio-basso', 'festa-braci-chiare', 'registro-sogni', 'lingua-nacreana'],
    searchHints: ['voci dormienti', 'memoria', 'sogni', 'archivio'],
  },
  {
    key: 'lingua-nacreana',
    title: 'Lingua nacreana dei registri sonori',
    kind: 'lore',
    tags: ['lore', 'lingua', 'Nacre', 'traduzione'],
    body: [
      'La lingua nacreana usa pause, inclinazioni e battiti leggeri come parte del testo. Una trascrizione alfabetica perde informazioni su intensita, direzione dello sguardo e ruolo del testimone.',
      'La spedizione porto campioni sonori incompleti. Selene propone di archiviarli come oggetti ibridi: documento, mappa e rito nello stesso record.',
    ],
    links: ['nacreani', 'osservatorio-nacre', 'spedizione-nacre', 'selene-registri'],
    searchHints: ['lingua nacreana', 'registri sonori', 'traduzione', 'Nacre'],
  },
  {
    key: 'diario-mercato',
    title: 'Diario operativo del mercato',
    kind: 'note',
    tags: ['nota', 'mercato', 'commercio', 'routine'],
    body: [
      'Annotazioni sparse raccolte durante settimane di mercato: prezzi del pesce, ritardi dei carri, umore degli scaricatori, arrivi dalla miniera e venditori che cambiano banco senza preavviso.',
      'La nota sembra ordinaria ma aiuta la ricerca semantica a collegare commercio, sale blu, porto e scioperi. Molte informazioni lunghe nascono proprio da dettagli ripetuti senza enfasi.',
    ],
    links: ['porto-vetro', 'compagnia-sale-blu', 'sciopero-battelli', 'appunti-cucina-molo'],
    searchHints: ['mercato', 'prezzi', 'commercio', 'routine'],
  },
  {
    key: 'checklist-riparazioni',
    title: 'Checklist riparazioni invernali',
    kind: 'note',
    tags: ['nota', 'manutenzione', 'inverno', 'controllo'],
    body: [
      'Controllare cerniere delle chiuse, corde dei contrappesi, vetro delle lampade, scorte di grasso, guanti cerati e percorsi asciutti per le squadre notturne.',
      'Segnare ogni intervento con tempo, odore della ruggine e nome del tecnico presente. Daro insiste che una checklist breve salva piu vite di un rapporto elegante scritto troppo tardi.',
    ],
    links: ['daro-chiuse', 'tecnico-chiuse', 'chiave-ruggine-dolce', 'incendio-diga-vecchia'],
    searchHints: ['checklist', 'riparazioni', 'inverno', 'chiuse'],
  },
  {
    key: 'appunti-cucina-molo',
    title: 'Appunti cucina del molo',
    kind: 'note',
    tags: ['nota', 'cucina', 'molo', 'quotidiano'],
    body: [
      'Zuppa di alghe chiare con lenticchie, pane tostato e olio di semi salmastri. Aggiungere foglie dell erbario solo dopo averle sciacquate tre volte, altrimenti il brodo diventa troppo metallico.',
      'Ricetta nata per turni lunghi al porto, utile come testo domestico e laterale rispetto alle note politiche. Dovrebbe risultare vicina a query su cibo, molo, piante e sale.',
    ],
    links: ['nima-serra', 'erbario-nima', 'diario-mercato', 'porto-vetro'],
    searchHints: ['cucina', 'molo', 'zuppa', 'piante salmastre'],
  },
  {
    key: 'registro-sogni',
    title: 'Registro sogni ricorrenti',
    kind: 'note',
    tags: ['nota', 'sogni', 'memoria', 'pattern'],
    body: [
      'Sogno ripetuto: un corridoio umido, una lampada fredda, cenere sotto i piedi e una voce che chiede di non aprire la terza porta. Variante comune dopo la festa delle braci chiare.',
      'I sogni non sono prova, ma diventano dati quando molte persone riportano la stessa sequenza. Collegare data, luogo, cibo consumato e vicinanza a registri sonori.',
    ],
    links: ['festa-braci-chiare', 'archivio-voci-dormienti', 'bosco-veyra', 'lampada-vetro-freddo'],
    searchHints: ['sogni ricorrenti', 'voce', 'lampada', 'festa'],
  },
  {
    key: 'segnale-non-classificato',
    title: 'Segnale non classificato sul canale tre',
    kind: 'custom',
    tags: ['custom', 'segnale', 'anomalia', 'rumore'],
    body: [
      'Segnale intermittente ascoltato sul canale tre durante una notte senza traffico. Pattern: tre impulsi bassi, pausa lunga, due fruscii simili a onde registrate al contrario.',
      'Non appartiene alle procedure portuali note. Potrebbe essere interferenza, registrazione nacreana danneggiata o codice usato da equipaggi che non vogliono passare dai mediatori.',
    ],
    links: ['lingua-nacreana', 'porto-vetro', 'maree-nere', 'orun-mastro'],
    searchHints: ['segnale', 'canale tre', 'anomalia', 'fruscio'],
  },
  {
    key: 'frammento-senza-provenienza',
    title: 'Frammento senza provenienza',
    kind: 'custom',
    tags: ['custom', 'frammento', 'prova', 'incerto'],
    body: [
      'Frammento di carta cerata con una linea di costa, tre punti blu e un numero senza unita di misura. Non ci sono firme, ma la pressione del tratto ricorda strumenti usati dai cartografi di maree.',
      'Da usare come distrattore quasi pertinente: sembra collegato a mappe, archivio e sale blu, ma nessun riferimento e abbastanza forte da chiudere il caso.',
    ],
    links: ['archivista-campo', 'mira-valen', 'gilda-bussole', 'miniera-sale-blu'],
    searchHints: ['frammento', 'provenienza incerta', 'mappe', 'prova'],
  },
] as const;
